### ISSUE TITLE
Add latest release tag

### ISSUE THREAD

**Issue by balasankarc** [bploetz/versionist#75]
Version 1.5.0 is missing from tag list. Please tag the commit.

**Comment by bploetz** [comment]
Done, but just curious why you care about the tag?

**Comment by balasankarc** [comment]
Thanks @bploetz.

I'm packaging versionist for Debian, as part of Diaspora packaging. We prefer the tests to be included in the package, and the gem file from rubygems.org doesn't have tests in it. So we have to use tarball from github. :)

**Comment by bploetz** [comment]
Well, there you go. Thanks for the explanation @balasankarc!
