### ISSUE TITLE
test error on Rails 5.0.1

### ISSUE THREAD

**Issue by ryancheung** [bploetz/versionist#80]
![image](https://cloud.githubusercontent.com/assets/240899/21759998/b11eac46-d683-11e6-99e7-5d62a57002d2.png)

**Comment by ryancheung** [comment]
app/controllers/v1/base_controller.rb:
```ruby
class V1::BaseController < ApplicationController
end
```

test/integration/v1/base_controller_test.rb: 
```ruby
require 'test_helper'

class V1::BaseControllerTest < ActionDispatch::IntegrationTest
  # Replace this with your real tests.
  test "the truth" do
    assert true
  end
end
```

**Comment by ryancheung** [comment]
Found it. There's alos a functional test class with the same class name in `test/functional/v1/base_controller_test.rb`:

```ruby
require 'test_helper'

class V1::BaseControllerTest < ActionController::TestCase
  # Replace this with your real tests.
  test "the truth" do
    assert true
  end
end
```

**Comment by ryancheung** [comment]
@bploetz I used the `versionist:new_api_version` generator to generate the template code.  Should the functional test class name be different with the integration test?

**Comment by bploetz** [comment]
versionist 1.6.0 has been released with the fix for this issue.
