### ISSUE TITLE
Rails 5 Support

### ISSUE THREAD

**Issue by chrishough** [bploetz/versionist#83]
I was curious if this gem is fully supported for rails 5+? My team wants to use it for a new service and one of our lead engineers noticed that it was a bit outdated. I have been using it in a separate application and it appears to work but I wanted to be sure.

**Comment by bploetz** [comment]
I mean, "outdated" is bit vague. The only issue I'm aware of is https://github.com/bploetz/versionist/pull/81, which should only effect the generators.

Versionist has been tested against Rails 5 for well over a year (https://github.com/bploetz/versionist/blob/master/gemfiles/Rails-5.0). If there's any Rails 5 specific issues I have not heard of them nor encountered them myself.

**Comment by locriani** [comment]
@chrishough We'll need to add a Rails 5.1 testing, and perhaps address the generator issue.

**Comment by bploetz** [comment]
I'd certainly welcome any PRs you guys may have. But for now, unless you've got a specific bug you've found in Rails 5, I'm gonna close this ticket. Thanks.

**Comment by locriani** [comment]
@bploetz Sounds good.
