### ISSUE TITLE
Is v2.0.0 a breaking change?

### ISSUE THREAD

**Issue by xtagon** [bploetz/versionist#89]
Hi,

I noticed v2.0.0 was released, but can't seem to find a changelog, or any info on the Releases page. Since it is a major version bump, are there any breaking changes to be aware of?

Thanks 👍

**Comment by bploetz** [comment]
Hey @xtagon this is due to Issue #88 . Since you can no longer use "Version" as a header value, I considered this a breaking change and bumped the major version.

**Comment by xtagon** [comment]
Makes sense! Thanks for the quick response and for following SemVer 👍
